//
//  MyTestColors.swift
//  (This file was autogenerated by RMRHexColorGen.  Do not modify as it can easily be overwritten.)

import UIKit

internal enum MyTestColors {

     internal enum ColorNames {

          static let myBlue: String = "MyBlue"
          static let myGrey: String = "MyGrey"
          static let myBlack: String = "MyBlack"
          static let primaryTextColor: String = "PrimaryTextColor"
     }


     static let myBlue: UIColor = UIColor(named:"MyBlue")!
     static let myGrey: UIColor = UIColor(named:"MyGrey")!
     static let myBlack: UIColor = UIColor(named:"MyBlack")!
     static let primaryTextColor: UIColor = UIColor(named:"PrimaryTextColor")!
}
