//
//  MyTestColors.swift
//  (This file was autogenerated by RMRHexColorGen, which parsed an input file of: Testing.palette.
//  Do not modify as it can easily be overwritten.)

import UIKit

internal enum MyTestColors {

     internal enum ColorNameConstants {

          static let myBlack: String = "MyBlack"
          static let myBlue: String = "MyBlue"
          static let myGrey: String = "MyGrey"
          static let berthaBlue: String = "BerthaBlue"
          static let primaryTextColor: String = "PrimaryTextColor"
     }


     //-------- Defined Colors with Provided Hex Values

     // #36383C -   BreakingIT!   Testing some shit here, eh?  Foakin' do it!!!
     static let myBlack: UIColor = UIColor(named: "MyBlack")!
     // #3D78FE
     static let myBlue: UIColor = UIColor(named: "MyBlue")!
     // #7C8089
     static let myGrey: UIColor = UIColor(named: "MyGrey")!


     //--------- Color Aliases who are references to defined colors above:

     // #3D78FE
     static let berthaBlue: UIColor = UIColor(named: "BerthaBlue")!
     // #36383C - BreakingIT! Testing some shit here, eh? Foakin' do it!!!
     static let primaryTextColor: UIColor = UIColor(named: "PrimaryTextColor")!
}
