//
//  NSColor+MyTestColors.h
//  (This file was autogenerated by RMRHexColorGen, which parsed an input file of: Testing.palette.
//  Do not modify as it can easily be overwritten.)
//

@import AppKit;


@interface NSColor (MyTestColors)

//-------- Defined Colors with Provided Hex Values

// #36383C -   BreakingIT!   Testing some shit here, eh?  Foakin' do it!!!
+ (NSColor *)t_myBlackColor;

// #3D78FE
+ (NSColor *)t_myBlueColor;

// #7C8089
+ (NSColor *)t_myGreyColor;



//-------- Color Aliases who are references to defined colors above:

// #3D78FE
+ (NSColor *)t_berthaBlueColor;

// #36383C - BreakingIT! Testing some shit here, eh? Foakin' do it!!!
+ (NSColor *)t_primaryTextColorColor;

@end
