//
//  UIColor+MyTestColors.h
//  (This file was autogenerated by RMRHexColorGen, which parsed an input file of: Testing.palette.
//  Do not modify as it can easily be overwritten.)
//

@import UIKit;


@interface UIColor (MyTestColors)

// #36383C -   BreakingIT!   Testing some shit here, eh?  Foakin' do it!!!
+ (UIColor *)t_myBlackColor
{
    return [UIColor colorWithRed:0.2117647081613541
                           green:0.2196078449487686
                            blue:0.2352941185235977
                           alpha:1];
}

// #3D78FE
+ (UIColor *)t_myBlueColor
{
    return [UIColor colorWithRed:0.239215686917305
                           green:0.4705882370471954
                            blue:0.9960784316062927
                           alpha:1];
}

// #7C8089
+ (UIColor *)t_myGreyColor
{
    return [UIColor colorWithRed:0.4862745106220245
                           green:0.501960813999176
                            blue:0.5372549295425415
                           alpha:1];
}

// #3D78FE
+ (UIColor *)t_berthaBlueColor
{
    return [UIColor colorWithRed:0.239215686917305
                           green:0.4705882370471954
                            blue:0.9960784316062927
                           alpha:1];
}

// #36383C - BreakingIT! Testing some shit here, eh? Foakin' do it!!!
+ (UIColor *)t_primaryTextColorColor
{
    return [UIColor colorWithRed:0.2117647081613541
                           green:0.2196078449487686
                            blue:0.2352941185235977
                           alpha:1];
}

@end
