//
//  UIColor+MyTestColors.h
//  (This file was autogenerated by RMRHexColorGen, which parsed an input file of: Testing.palette.
//  Do not modify as it can easily be overwritten.)
//

@import UIKit;


@interface UIColor (MyTestColors)

//-------- Defined Colors with Provided Hex Values

// ##36383C -  BreakingIT!   Testing some stuff here.
+ (UIColor *)test_myBlackColor;

// ##3D78FE - Basic Blue for the app
+ (UIColor *)test_myBlueColor;

// ##7C8089
+ (UIColor *)test_myGreyColor;



//-------- Color Aliases who are references to defined colors above:

// ##3D78FE
+ (UIColor *)test_primaryAppColorColor;

// ##36383C - BreakingIT! Testing some stuff here.
+ (UIColor *)test_primaryTextColorColor;

@end
