//
//  UIColor+MyTestColors.m
//  (This file was autogenerated by RMRHexColorGen, which parsed an input file of: Testing.palette.
//  Do not modify as it can easily be overwritten.)
//

#import "UIColor+MyTestColors.h"


@implementation UIColor (MyTestColors)

// ##36383C -  BreakingIT!   Testing some stuff here.
+ (UIColor *)test_myBlackColor
{
    return [UIColor colorNamed:MyBlack];
}

// ##3D78FE - Basic Blue for the app
+ (UIColor *)test_myBlueColor
{
    return [UIColor colorNamed:MyBlue];
}

// ##7C8089
+ (UIColor *)test_myGreyColor
{
    return [UIColor colorNamed:MyGrey];
}

// ##3D78FE
+ (UIColor *)test_primaryAppColorColor
{
    return [UIColor colorNamed:PrimaryAppColor];
}

// ##36383C - BreakingIT! Testing some stuff here.
+ (UIColor *)test_primaryTextColorColor
{
    return [UIColor colorNamed:PrimaryTextColor];
}

@end
