//
//  GeneratedColors.swift
//  (This file was autogenerated by RMRHexColorGen, which parsed an input file of: AppColors.palette.
//  Do not modify as it can easily be overwritten.)

import UIKit

internal enum GeneratedColors {

     //-------- Defined Colors with Provided Hex Values

    /// #36383C -  BreakingIT!   Testing some stuff here.
     static let myBlack: UIColor = UIColor(named: "MyBlack")!
    /// #3D78FE - Basic Blue for the app
     static let myBlue: UIColor = UIColor(named: "MyBlue")!
    /// #7C8089
     static let myGrey: UIColor = UIColor(named: "MyGrey")!


     //--------- Color Aliases who are references to defined colors above:

    /// #3D78FE
     static let primaryAppColor: UIColor = UIColor(named: "PrimaryAppColor")!
    /// #36383C - BreakingIT! Testing some stuff here.
     static let primaryTextColor: UIColor = UIColor(named: "PrimaryTextColor")!


     //--------- Constants used for named colors (you will likely never need them but here for completeness)
     internal enum Name {

          static let myBlack: String = "MyBlack"
          static let myBlue: String = "MyBlue"
          static let myGrey: String = "MyGrey"
          static let primaryAppColor: String = "PrimaryAppColor"
          static let primaryTextColor: String = "PrimaryTextColor"
     }
}
